name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-links:
    name: Validate Markdown Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          folder-path: "."
          file-extension: ".md"
